import {
    AlignmentType,
    Document,
    Footer,
    Header,
    HeadingLevel,
    Packer,
    PageNumber,
    Paragraph,
    ShadingType,
    Table,
    TableCell,
    TableRow,
    TableLayoutType,
    TextRun,
    WidthType,
    BorderStyle
} from 'docx';

const LABELS = {
    en: {
        docTitle: 'Lesson Plan',
        teacher: 'Teacher',
        class: 'Class',
        subject: 'Subject',
        date: 'Date',
        week: 'Week',
        topic: 'Topic',
        status: 'Status',
        summary: 'Summary',
        description: 'Description',
        previousKnowledge: 'Previous Knowledge',
        teachingObjectives: 'Teaching Objectives',
        learningObjectives: 'Learning Objectives',
        objectives: 'Objectives',
        vocabulary: 'Vocabulary',
        characterTraitLinks: 'Character Trait Links',
        techIntegration: 'Technology Integration',
        stages: 'Lesson Stages',
        stageNo: '#',
        stageName: 'Stage',
        procedure: 'Procedure',
        materials: 'Materials',
        timing: 'Timing',
        standards: 'Standards',
        activities: 'Activities',
        assessmentMethods: 'Assessment Methods',
        resources: 'Resources',
        differentiation: 'Differentiation',
        homework: 'Homework',
        notes: 'Notes',
        generated: 'Generated by ClassHope',
        page: 'Page',
        none: '—',
        statuses: {
            draft: 'Draft',
            submitted: 'Submitted',
            approved: 'Approved',
            needs_revision: 'Needs revision',
            rejected: 'Rejected'
        }
    },
    ar: {
        docTitle: 'خطة الدرس',
        teacher: 'المعلم',
        class: 'الصف',
        subject: 'المادة',
        date: 'التاريخ',
        week: 'الأسبوع',
        topic: 'الموضوع',
        status: 'الحالة',
        summary: 'الملخص',
        description: 'الوصف',
        previousKnowledge: 'المعرفة السابقة',
        teachingObjectives: 'أهداف التدريس',
        learningObjectives: 'أهداف التعلم',
        objectives: 'الأهداف',
        vocabulary: 'المفردات',
        characterTraitLinks: 'ربط السمات الشخصية',
        techIntegration: 'دمج التكنولوجيا',
        stages: 'مراحل الدرس',
        stageNo: 'م',
        stageName: 'المرحلة',
        procedure: 'الإجراءات',
        materials: 'المواد',
        timing: 'الوقت',
        standards: 'المعايير',
        activities: 'الأنشطة',
        assessmentMethods: 'أساليب التقييم',
        resources: 'المصادر',
        differentiation: 'التمايز',
        homework: 'الواجب المنزلي',
        notes: 'ملاحظات',
        generated: 'تم الإنشاء بواسطة ClassHope',
        page: 'صفحة',
        none: '—',
        statuses: {
            draft: 'مسودة',
            submitted: 'مُرسلة',
            approved: 'معتمدة',
            needs_revision: 'تحتاج إلى مراجعة',
            rejected: 'مرفوضة'
        }
    }
};

const FONT = 'Arial';

// A4 page, 1000-twip margins. All table widths are absolute (DXA) and must sum to CONTENT_WIDTH.
const PAGE_WIDTH = 11906;
const PAGE_HEIGHT = 16838;
const PAGE_MARGIN = 1000;
const CONTENT_WIDTH = PAGE_WIDTH - PAGE_MARGIN * 2;
const INFO_COLS = [1700, 3253, 1700, 3253];
const STAGE_COLS = [600, 1900, 4206, 2000, 1200];
const BORDER = { style: BorderStyle.SINGLE, size: 4, color: 'CBD5E1' };
const CELL_BORDERS = { top: BORDER, bottom: BORDER, left: BORDER, right: BORDER };
const HEADER_FILL = { type: ShadingType.CLEAR, color: 'auto', fill: 'E8F1EC' };

// Strip characters that are invalid in XML 1.0 and any markup
const clean = (value) => String(value ?? '')
    .replace(/<[^>]*>/g, '')
    .replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g, '')
    .trim();

const BULLET_PATTERN = /^\s*(?:[-•*]|\d+[.)])\s+/;

export const buildSafeFilename = (title, date) => {
    const base = clean(title)
        .replace(/[\\/:*?"<>|\r\n]+/g, ' ')
        .replace(/\s+/g, ' ')
        .trim()
        .slice(0, 100) || 'lesson-plan';
    const day = date ? new Date(date).toISOString().slice(0, 10) : '';
    return `${base}${day ? `-${day}` : ''}.docx`;
};

export const buildLessonPlanDocx = async (plan, options = {}) => {
    const lang = options.lang === 'ar' ? 'ar' : 'en';
    const isArabic = lang === 'ar';
    const L = LABELS[lang];
    const align = isArabic ? AlignmentType.RIGHT : AlignmentType.LEFT;

    const run = (text, extra = {}) => new TextRun({
        text,
        font: FONT,
        rightToLeft: isArabic,
        size: 22,
        ...extra
    });

    const para = (text, extra = {}) => new Paragraph({
        bidirectional: isArabic,
        alignment: align,
        spacing: { after: 80 },
        children: [run(text, extra.run)],
        ...extra.paragraph
    });

    // One paragraph per line; bullet-like lines become real list items
    const textParagraphs = (value) => {
        const text = clean(value);
        if (!text) return [para(L.none)];
        return text.split(/\r?\n/).filter((line) => line.trim()).map((line) => {
            if (BULLET_PATTERN.test(line)) {
                return new Paragraph({
                    bidirectional: isArabic,
                    alignment: align,
                    bullet: { level: 0 },
                    spacing: { after: 60 },
                    children: [run(line.replace(BULLET_PATTERN, ''))]
                });
            }
            return para(line);
        });
    };

    const heading = (text) => new Paragraph({
        heading: HeadingLevel.HEADING_2,
        bidirectional: isArabic,
        alignment: align,
        spacing: { before: 240, after: 100 },
        children: [run(text, { bold: true, size: 26, color: '1F5F46' })]
    });

    const cell = (children, extra = {}) => new TableCell({
        borders: CELL_BORDERS,
        margins: { top: 60, bottom: 60, left: 100, right: 100 },
        children: Array.isArray(children) ? children : [children],
        ...extra
    });

    // Google Docs ignores percentage widths, so every table uses absolute DXA widths
    // that sum to the content width, plus an explicit grid and fixed layout.
    const makeTable = (columnWidths, rows) => {
        const total = columnWidths.reduce((a, b) => a + b, 0);
        if (total !== CONTENT_WIDTH) {
            throw new Error(`Table column widths sum to ${total}, expected ${CONTENT_WIDTH}`);
        }
        return new Table({
            width: { size: CONTENT_WIDTH, type: WidthType.DXA },
            columnWidths,
            layout: TableLayoutType.FIXED,
            visuallyRightToLeft: isArabic,
            rows
        });
    };

    const headerCell = (text, width) => cell(
        para(text, { run: { bold: true } }),
        { shading: HEADER_FILL, width: { size: width, type: WidthType.DXA } }
    );

    const sections = [];

    const infoPairs = [
        [L.teacher, options.teacherName],
        [L.class, options.className],
        [L.subject, options.subjectName],
        [L.date, plan.date
            ? new Date(plan.date).toLocaleDateString(isArabic ? 'ar-EG' : 'en-US', {
                year: 'numeric', month: 'long', day: 'numeric'
            })
            : ''],
        [L.week, plan.weekNumber],
        [L.topic, plan.topic],
        [L.status, L.statuses[plan.status] || plan.status]
    ].filter(([, value]) => clean(value));

    const infoRows = [];
    for (let i = 0; i < infoPairs.length; i += 2) {
        const pair = [infoPairs[i], infoPairs[i + 1]];
        const cells = [];
        pair.forEach((entry) => {
            cells.push(
                cell(para(entry ? entry[0] : '', { run: { bold: true } }), { shading: HEADER_FILL, width: { size: INFO_COLS[cells.length], type: WidthType.DXA } }),
                cell(para(entry ? clean(entry[1]) : ''), { width: { size: INFO_COLS[cells.length + 1], type: WidthType.DXA } })
            );
        });
        infoRows.push(new TableRow({ children: cells }));
    }

    sections.push(new Paragraph({
        alignment: AlignmentType.CENTER,
        bidirectional: isArabic,
        spacing: { after: 60 },
        children: [run(clean(options.schoolName), { bold: true, size: 28, color: '1F5F46' })]
    }));
    sections.push(new Paragraph({
        alignment: AlignmentType.CENTER,
        bidirectional: isArabic,
        spacing: { after: 60 },
        children: [run(L.docTitle, { size: 24, color: '52675F' })]
    }));
    sections.push(new Paragraph({
        alignment: AlignmentType.CENTER,
        bidirectional: isArabic,
        heading: HeadingLevel.TITLE,
        spacing: { after: 200 },
        children: [run(clean(plan.title), { bold: true, size: 36 })]
    }));

    if (infoRows.length) {
        sections.push(makeTable(INFO_COLS, infoRows));
    }

    const textSections = [
        [L.summary, plan.summary],
        [L.description, plan.description],
        [L.previousKnowledge, plan.previousKnowledge],
        [L.teachingObjectives, plan.teachingObjectives],
        [L.learningObjectives, plan.learningObjectives]
    ];
    textSections.forEach(([title, value]) => {
        if (!clean(value)) return;
        sections.push(heading(title), ...textParagraphs(value));
    });

    const objectives = (plan.objectives || []).filter((o) => clean(o?.text));
    if (objectives.length) {
        sections.push(heading(L.objectives));
        objectives
            .slice()
            .sort((a, b) => (a.order || 0) - (b.order || 0))
            .forEach((objective, index) => {
                sections.push(new Paragraph({
                    bidirectional: isArabic,
                    alignment: align,
                    spacing: { after: 60 },
                    children: [run(`${index + 1}. ${clean(objective.text)}`)]
                }));
            });
    }

    [
        [L.vocabulary, plan.vocabulary],
        [L.characterTraitLinks, plan.characterTraitLinks],
        [L.techIntegration, plan.techIntegration]
    ].forEach(([title, value]) => {
        if (!clean(value)) return;
        sections.push(heading(title), ...textParagraphs(value));
    });

    const stages = (plan.stages || []).filter((s) => s && (clean(s.name) || clean(s.procedure) || clean(s.materials) || clean(s.timing)));
    if (stages.length) {
        sections.push(heading(L.stages));
        const widths = STAGE_COLS;
        const headerRow = new TableRow({
            tableHeader: true,
            children: [L.stageNo, L.stageName, L.procedure, L.materials, L.timing]
                .map((text, i) => headerCell(text, widths[i]))
        });
        const rows = stages.map((stage, index) => new TableRow({
            cantSplit: true,
            children: [
                String(index + 1), stage.name, stage.procedure, stage.materials, stage.timing
            ].map((value, i) => cell(textParagraphs(value), { width: { size: widths[i], type: WidthType.DXA } }))
        }));
        sections.push(makeTable(widths, [headerRow, ...rows]));
    }

    const standards = [
        ...(options.standards || []).map((s) => [s.code, s.name].filter(Boolean).join(' — ')),
        ...(plan.manualStandards || []).map((s) => [s.code, s.name || s.description].filter(Boolean).join(' — '))
    ].map(clean).filter(Boolean);
    if (standards.length) {
        sections.push(heading(L.standards));
        standards.forEach((line) => sections.push(new Paragraph({
            bidirectional: isArabic,
            alignment: align,
            bullet: { level: 0 },
            spacing: { after: 60 },
            children: [run(line)]
        })));
    }

    [
        [L.activities, plan.activities],
        [L.assessmentMethods, plan.assessmentMethods],
        [L.resources, plan.resources],
        [L.differentiation, plan.differentiation],
        [L.homework, plan.homework],
        [L.notes, plan.notes]
    ].forEach(([title, value]) => {
        if (!clean(value)) return;
        sections.push(heading(title), ...textParagraphs(value));
    });

    const footerRun = (extra = {}) => ({ font: FONT, size: 16, color: '64748B', rightToLeft: isArabic, ...extra });
    const doc = new Document({
        creator: 'ClassHope',
        title: clean(plan.title),
        sections: [{
            properties: {
                page: {
                    size: { width: PAGE_WIDTH, height: PAGE_HEIGHT },
                    margin: { top: PAGE_MARGIN, bottom: PAGE_MARGIN, left: PAGE_MARGIN, right: PAGE_MARGIN }
                }
            },
            headers: {
                default: new Header({
                    children: [new Paragraph({
                        alignment: AlignmentType.CENTER,
                        children: [new TextRun(footerRun({ text: clean(options.schoolName) }))]
                    })]
                })
            },
            footers: {
                default: new Footer({
                    children: [new Paragraph({
                        alignment: AlignmentType.CENTER,
                        children: [
                            new TextRun(footerRun({ text: `${L.generated} · ${L.page} ` })),
                            new TextRun(footerRun({ children: [PageNumber.CURRENT] }))
                        ]
                    })]
                })
            },
            children: sections
        }]
    });

    return Packer.toBuffer(doc);
};
