import mongoose from "mongoose";
import { tenantIsolationPlugin } from "../middleware/tenantIsolation.js";

/**
 * NewsletterSection
 * One subject section per class/week (per issue), generated by a teacher and reviewed by admin.
 */
const newsletterSectionSchema = new mongoose.Schema(
  {
    school: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "School",
      required: true,
      index: true,
    },
    issue: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "NewsletterIssue",
      required: true,
      index: true,
    },
    class: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Class",
      required: true,
      index: true,
    },
    subject: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Subject",
      required: true,
      index: true,
    },

    teacherUser: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    teacherProfile: { type: mongoose.Schema.Types.ObjectId, ref: "Teacher" },

    language: {
      type: String,
      enum: ["english", "arabic", "bilingual"],
      default: "english",
      index: true,
    },

    selectedLessonPlanIds: [
      { type: mongoose.Schema.Types.ObjectId, ref: "LessonPlan" },
    ],

    // The 100–120 word newsletter content for this subject.
    content: { type: String, default: "" },
    wordCount: { type: Number, default: 0 },
    keyTopics: [{ type: String }],
    homeworkMentioned: { type: Boolean, default: false },

    /**
     * Token usage is centralized in AITokenUsage.
     * Store only a reference here (no duplicated counts).
     */
    aiTokenUsage: { type: mongoose.Schema.Types.ObjectId, ref: "AITokenUsage" },

    status: {
      type: String,
      enum: ["draft", "submitted", "approved", "rejected"],
      default: "draft",
      index: true,
    },

    submittedAt: { type: Date },

    adminReview: {
      reviewedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
      reviewedAt: { type: Date },
      notes: { type: String, default: "" },
    },
  },
  { timestamps: true }
);

// One section per subject per issue (per class/week)
newsletterSectionSchema.index(
  { school: 1, issue: 1, class: 1, subject: 1 },
  { unique: true }
);

newsletterSectionSchema.plugin(tenantIsolationPlugin);

const NewsletterSection = mongoose.model(
  "NewsletterSection",
  newsletterSectionSchema
);
export default NewsletterSection;

